In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x=np.arange(4,dtype=np.int64)
k=x.shape
a=np.ones(k)
a

array([1., 1., 1., 1.])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X=np.array([[1,2],[3,4]])
X=np.asmatrix(x)
X

matrix([[0, 1, 2, 3]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
A=np.linspace(3,10)
A

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]]) 
new_arr = np.stack((x[0],x[1]), axis=1)
new_arr.reshape(6,)

array([1, 4, 2, 5, 3, 6])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
x1=np.array(x[:4])
x2=np.array(x[4:6])
x3=np.array(x[6:])
print(x1)
print(x2)
print(x3)

[1 2 3 4]
[5 6]
[7 8 9]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=[[1,2],[3,4]]
inverse=np.linalg.inv(x)
print(inverse)
print(np.trace(x))

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
 x = [[1,4],[3,1]]
np.sort(x,axis=1)

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x = [[1,4],[3,1]]
y = np.argsort(x, axis=1)
y

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
from numpy import random

x = random.randint(10, size=(2, 5))
y=np.argmax(x,axis=1)
z=np.argmin(x,axis=1)
print(y)
print(z)

[1 1]
[2 0]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
import pandas as pd
iris_2d=pd.DataFrame(iris_2d)
iris_2d

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
iris_2d.isna().sum()

0    0
1    0
2    0
3    0
dtype: int64

In [ ]:
iris_2d.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

Find the correlation between first two columns.

In [ ]:
col1=iris_2d[0]
col2=iris_2d[1]
correlation=col1.corr(col2)
print(correlation)

-0.10936924995064937


Find the mean,median and standard deviation of column 3.

In [ ]:
print("mean",iris_2d[3].mean())
print("median",iris_2d[3].median())
print("standard deviation",iris_2d[3].std())

mean 1.1986666666666672
median 1.3
standard deviation 0.7631607417008414


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
iris_2d["volume"]=(np.pi*iris_2d[2]*(iris_2d[0]**2))/3
iris_2d

0    1    2    3      volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris = np.genfromtxt(url, delimiter=',', dtype='object')

Find the count of unique species.

In [ ]:
iris=pd.DataFrame(iris)
iris.columns=names
iris

sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]

In [ ]:
k=set(list(iris['species']))
unique_species=len(k)
print("number of unique species:",unique_species)

number of unique species: 3


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
bins=np.digitize(iris["petallength"].astype("float"),[0,3,5,10])
textmapping={1:"small",2:"medium",3:"large"}
k=[textmapping[x] for x in bins]
k

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
A=set(list(iris["petallength"]))
B=list(iris["petallength"])
m=0
c=0
for i in A:
  if(B.count(i)>m):
    c=i
    m=B.count(i)
print(c)

b'1.5'


In [ ]:
iris["petallength"].mode()

0    b'1.5'
dtype: object